<?php
class config
{
    public $Id,$Title,$Title_en,$Keyword,$Description,$Logo,$Logo_footer,$Icon,$Name,$Name_en,$Address,$Address_en,$Phone,$Hotline,$Hotlien_datve,$Email,$Website,$Skype,$Yahoo;
    public function config($data=array())
    {
    $this->Id=isset($data['Id'])?$data['Id']:'';
    $this->Title=isset($data['Title'])?$data['Title']:'';
    $this->Title_en=isset($data['Title_en'])?$data['Title_en']:'';
    $this->Keyword=isset($data['Keyword'])?$data['Keyword']:'';
    $this->Description=isset($data['Description'])?$data['Description']:'';
    $this->Logo=isset($data['Logo'])?$data['Logo']:'';
    $this->Logo_footer=isset($data['Logo_footer'])?$data['Logo_footer']:'';
    $this->Icon=isset($data['Icon'])?$data['Icon']:'';
    $this->Name=isset($data['Name'])?$data['Name']:'';
    $this->Name_en=isset($data['Name_en'])?$data['Name_en']:'';
    $this->Address=isset($data['Address'])?$data['Address']:'';
    $this->Address_en=isset($data['Address_en'])?$data['Address_en']:'';
    $this->Phone=isset($data['Phone'])?$data['Phone']:'';
    $this->Hotline=isset($data['Hotline'])?$data['Hotline']:'';
    $this->Hotlien_datve=isset($data['Hotlien_datve'])?$data['Hotlien_datve']:'';
    $this->Email=isset($data['Email'])?$data['Email']:'';
    $this->Website=isset($data['Website'])?$data['Website']:'';
    $this->Skype=isset($data['Skype'])?$data['Skype']:'';
    $this->Yahoo=isset($data['Yahoo'])?$data['Yahoo']:'';
          $this->encode();
    }
    public function encode()
        {
            $this->Id=addslashes($this->Id);
            $this->Title=addslashes($this->Title);
            $this->Title_en=addslashes($this->Title_en);
            $this->Keyword=addslashes($this->Keyword);
            $this->Description=addslashes($this->Description);
            $this->Logo=addslashes($this->Logo);
            $this->Logo_footer=addslashes($this->Logo_footer);
            $this->Icon=addslashes($this->Icon);
            $this->Name=addslashes($this->Name);
            $this->Name_en=addslashes($this->Name_en);
            $this->Address=addslashes($this->Address);
            $this->Address_en=addslashes($this->Address_en);
            $this->Phone=addslashes($this->Phone);
            $this->Hotline=addslashes($this->Hotline);
            $this->Hotlien_datve=addslashes($this->Hotlien_datve);
            $this->Email=addslashes($this->Email);
            $this->Website=addslashes($this->Website);
            $this->Skype=addslashes($this->Skype);
            $this->Yahoo=addslashes($this->Yahoo);
        }
    public function decode()
        {
            $this->Id=stripslashes($this->Id);
            $this->Title=stripslashes($this->Title);
            $this->Title_en=stripslashes($this->Title_en);
            $this->Keyword=stripslashes($this->Keyword);
            $this->Description=stripslashes($this->Description);
            $this->Logo=stripslashes($this->Logo);
            $this->Logo_footer=stripslashes($this->Logo_footer);
            $this->Icon=stripslashes($this->Icon);
            $this->Name=stripslashes($this->Name);
            $this->Name_en=stripslashes($this->Name_en);
            $this->Address=stripslashes($this->Address);
            $this->Address_en=stripslashes($this->Address_en);
            $this->Phone=stripslashes($this->Phone);
            $this->Hotline=stripslashes($this->Hotline);
            $this->Hotlien_datve=stripslashes($this->Hotlien_datve);
            $this->Email=stripslashes($this->Email);
            $this->Website=stripslashes($this->Website);
            $this->Skype=stripslashes($this->Skype);
            $this->Yahoo=stripslashes($this->Yahoo);
        }
}
