insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('1','Combo booking','Combo booking','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu1.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon1.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt1.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Combo booking','Combo booking','Combo booking','Combo booking');
insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('2','Đặt phòng khách sạn','Hotel booking','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu2.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon2.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt2.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Đặt phòng khách sạn','Hotel booking','Đặt phòng khách sạn','Đặt phòng khách sạn');
insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('3','Du thuyền','Yatch','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu3.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon3.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt3.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Du thuyền','Yatch','Du thuyền','Du thuyền');
insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('4','Tour du lịch','Tour','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu4.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon4.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt4.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Tour duc lịch','Tour','Tour duc lịch','Tour duc lịch');
insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('5','Dịch vụ vận tải - cho thuê xe','Transportation services - rental car','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu5.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon5.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt5.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Dịch vụ vận tải - cho thuê xe','Transportation services - rental car','Dịch vụ vận tải - cho thuê xe','Dịch vụ vận tải - cho thuê xe');
insert into dichvu (ViTri,Name,Name_en,Img,MoTaNgan,MoTaNgan_en,NoiDung,NoiDung_en,Icon,Icon_gioithieu,Avatar,Name_ht,MoTaNgan_ht,MoTaNgan_ht_en,Phone,Email,Yahoo,Skype,Title,Title_en,Keyword,Description) values ('6','Đặt vé tàu hỏa','Booking train tickets','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/dichvu6.png','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. ','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum link in paragraph suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, link:hover. Maecenas a odio turpis. Morbi sed dolor link:visited, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque malesuada faucibus justo. Donec ipsum erat, feugiat vitae ullamcorper nec, venenatis quis velit. Nulla felis odio, vestibulum in magna eu, faucibus porttitor diam. Aenean vehicula, lorem nec tempus luctus, neque est suscipit orci, vitae vehicula dui mauris eget elit. Donec quis justo condimentum massa tempor sagittis. Duis malesuada lectus non magna vulputate pellentesque. Nam nisl quam, semper rhoncus orci eu, fermentum sagittis mauris. Nunc pellentesque et erat id egestas.</p>
<p>
	Pellentesque imperdiet sollicitudin scelerisque. Mauris accumsan tellus venenatis lectus rutrum, in egestas purus feugiat. Vestibulum arcu sapien, scelerisque non tincidunt id, pretium vitae nibh. Vestibulum ac suscipit sem, sit amet vestibulum nibh. Integer euismod id massa aliquam tempor. Aenean ac elementum nisl. Praesent erat nisi, imperdiet eu diam ac, pellentesque volutpat est. Donec nunc mi, accumsan feugiat ullamcorper et, ornare nec neque. Maecenas a odio turpis. Morbi sed dolor elementum, gravida magna eget, convallis eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia.<br />
	Donec posuere iaculis erat, id ullamcorper nibh pretium mollis. Integer quam mauris, varius vel pretium eleifend, vestibulum a ante. Cras posuere quam sed lorem porttitor, in ornare erat dignissim. Etiam rhoncus velit ac facilisis dignissim. Quisque</p>
','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon/icon6.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/icon_gt/icon_gt6.png','/pi_maybay/view/admin/Themes/kcfinder/upload/images/dichvu/avatar/avatar.png','Mrs Tuyến','<p>
	Hỗ trợ hướng dẫn đặt tour l&agrave;m sao để đặt ph&ograve;ng kh&aacute;ch sạn tại mạng du lịch trực tuyến TOURCOACH để được đặt ph&ograve;ng qu&yacute; kh&aacute;ch vui l&ograve;ng đăng k&yacute; tại đ&acirc;y hoặc qu&yacute; kh&aacute;ch vui l&ograve;ng li&ecirc;n hệ với ch&uacute;ng t&ocirc;i để được tư vấn v&agrave; hướng dẫn trực tiếp.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Supports</span> <span class=\"hps\">tour</span> <span class=\"hps\">guide</span> <span class=\"hps\">how</span> <span class=\"hps\">to book</span> <span class=\"hps\">hotels</span> <span class=\"hps\">online travel</span> <span class=\"hps\">network</span> <span class=\"hps\">to</span> <span class=\"hps\">be</span> <span class=\"hps\">booked</span> <span class=\"hps\">TOURCOACH</span> <span class=\"hps\">please</span> <span class=\"hps\">register here</span> <span class=\"hps\">or</span> <span class=\"hps\">please</span> <span class=\"hps\">contact</span> <span class=\"hps\">us</span> <span class=\"hps\">for advice</span> <span class=\"hps\">and</span> <span class=\"hps\">guidance</span> <span class=\"hps\">online</span> <span class=\"hps\">next</span><span>.</span></span></p>
','094 998 0762','tourcoach2013@gmail.com','tvt_hut','tungphongtom','Đặt vé tàu hỏa','Booking train tickets','Đặt vé tàu hỏa','Đặt vé tàu hỏa');
