insert into gioithieu (Name,GioiThieu,GioiThieu_en,UuViet,UuViet_en,CacDichVu,CacDicVu_en,CamKet,CamKet_en) values ('Thông tin giới thiệu','<p>
	TOURCOACH chuy&ecirc;n cung cấp dịch vụ đặt v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa v&agrave; quốc tế với c&aacute;c chức năng ưu việt: t&igrave;m kiếm h&agrave;nh tr&igrave;nh bay, giờ bay, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng, đặt v&eacute; tr&ecirc;n website v&agrave; thanh to&aacute;n trực tuyến.</p>
<p>
	Tourcoach được h&agrave;nh lập năm 2014 bởi C&Ocirc;NG TY TNHH DỊCH VỤ - VẬN TẢI V&Agrave; LỮ H&Agrave;NH QUỐC TẾ COACH, ch&uacute;ng t&ocirc;i đ&atilde; lựa chọn sứ mệnh phục vụ kh&aacute;ch h&agrave;ng mang đến những chuyến bay &ldquo;Chi ph&iacute; hợp l&yacute; &ndash; Chuyến đi như &yacute;&rdquo; - đ&oacute; ch&iacute;nh l&agrave; sự kh&aacute;c biệt của Tourcoach.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">TOURCOACH</span> <span class=\"hps\">specializes in providing</span> <span class=\"hps\">services</span> <span class=\"hps\">online</span> <span class=\"hps\">ticket booking</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span> <span class=\"hps\">domestic</span> <span class=\"hps\">and</span> <span class=\"hps\">international</span> <span class=\"hps\">with</span> <span class=\"hps\">Vietnam</span> <span class=\"hps\">enhanced functions</span><span>:</span> <span class=\"hps\">search for</span> <span class=\"hps\">the flight</span><span>,</span> <span class=\"hps\">flight times</span><span>,</span> <span class=\"hps\">compare</span> <span class=\"hps\">fares</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span><span>, ticketing</span> <span class=\"hps\">on the website</span> <span class=\"hps\">and</span> <span class=\"hps\">pay online</span><span>.</span><br />
	<br />
	<span class=\"hps\">Tourcoach</span> <span class=\"hps\">was</span> <span class=\"hps\">founded</span> <span class=\"hps\">in 2014</span> <span class=\"hps\">by</span> <span class=\"hps\">executive</span> <span class=\"hps\">SERVICES LIMITED</span> <span class=\"hps\">COMPANY</span> <span class=\"hps\">-</span> <span class=\"hps\">TRANSPORTATION AND</span> <span class=\"hps\">TRAVEL</span> <span class=\"hps\">INTERNATIONAL</span> <span class=\"hps\">COACH</span><span>,</span> <span class=\"hps\">we</span> <span class=\"hps\">have chosen</span> <span class=\"hps\">the mission</span> <span class=\"hps\">to serve customers</span> <span class=\"hps\">bring</span> <span class=\"hps\">flight</span> <span class=\"hps atn\">&quot;</span><span>Reasonable expenses</span> <span class=\"hps\">-</span> <span class=\"hps\">Trips</span> <span class=\"hps\">like that</span><span>&quot;</span> <span class=\"hps\">-</span> <span class=\"hps\">that is the</span> <span class=\"hps\">difference</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span><span>.</span></span></p>
','<p>
	Tiết kiệm thời gian: Tourcoach li&ecirc;n tục cập nhật c&aacute;c th&ocirc;ng tin về tất cả c&aacute;c chuyến bay, giờ bay, gi&aacute; v&eacute; của 3 h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, 300 h&atilde;ng h&agrave;ng kh&ocirc;ng quốc tế. Qu&yacute; kh&aacute;ch sẽ kh&ocirc;ng cần phải tốn thời gian truy cập v&agrave;o trang b&aacute;n v&eacute; trực tuyến của từng h&atilde;ng h&agrave;ng kh&ocirc;ng, chỉ cần một v&agrave;i c&uacute; click chuột tra cứu th&ocirc;ng tin, qu&yacute; kh&aacute;ch sẽ dễ d&agrave;ng t&igrave;m kiếm được h&agrave;nh tr&igrave;nh bay, so s&aacute;nh gi&aacute; v&eacute; v&agrave; thực hiện thao t&aacute;c đặt v&eacute;, thanh to&aacute;n trực tuyến một c&aacute;ch nhanh ch&oacute;ng. Tiết kiệm chi ph&iacute;: Việc cập nhật c&aacute;c th&ocirc;ng tin khuyến m&atilde;i, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng sẽ gi&uacute;p Qu&yacute; kh&aacute;ch lựa chọn được chuyến bay c&oacute; mức chi ph&iacute; tiết kiệm nhất ph&ugrave; hợp với nhu cầu của m&igrave;nh. Gi&aacute; v&eacute; m&aacute;y bay tốt nhất lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng cho Qu&yacute; kh&aacute;ch lựa chọn khi đặt dịch vụ ở Tourcoach.</p>
<p>
	Dễ d&agrave;ng sử dụng: Qu&yacute; kh&aacute;ch c&oacute; thể t&igrave;m thấy những th&ocirc;ng tin hữu &iacute;ch về v&eacute; m&aacute;y bay ở Tourcoach qua từng chuy&ecirc;n mục: T&igrave;m kiếm chuyến bay, V&eacute; Quốc tế, V&eacute; Nội địa, Tin khuyến mại, V&eacute; m&aacute;y bay theo chặng h&agrave;nh tr&igrave;nh, V&eacute; m&aacute;y bay theo h&atilde;ng h&agrave;ng kh&ocirc;ng để c&oacute; thể lựa chọn h&agrave;nh tr&igrave;nh bay ph&ugrave; hợp với m&igrave;nh.</p>
<p>
	Dịch vụ kh&aacute;ch h&agrave;ng chuy&ecirc;n nghiệp, tận t&igrave;nh: Đến với Vegiare, Qu&yacute; kh&aacute;ch lu&ocirc;n được đ&oacute;n ch&agrave;o nồng nhiệt, phục vụ chu đ&aacute;o bởi đội ngũ nh&acirc;n vi&ecirc;n chuy&ecirc;n nghiệp, gi&agrave;u nhiệt huyết v&agrave; giỏi chuy&ecirc;n m&ocirc;n. Hệ thống chăm s&oacute;c kh&aacute;ch h&agrave;ng 24/7 lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng gải đ&aacute;p mọi thắc mắc v&agrave; hỗ trợ Qu&yacute; kh&aacute;ch về mặt nghiệp vụ.</p>
<p>
	Thanh to&aacute;n nhanh ch&oacute;ng, linh hoạt v&agrave; an to&agrave;n: Qu&yacute; kh&aacute;ch c&oacute; thể thanh to&aacute;n trực tiếp qua chuyển khoản, tiền mặt. Hệ thống thanh to&aacute;n trực tuyến cho ph&eacute;p thanh to&aacute;n bằng thẻ quốc tế Visa, Master Card, thẻ ng&acirc;n h&agrave;ng nội địa hoặc thanh to&aacute;n qua mobile banking. Hệ thống bảo mật của Tourcoach cam kết sẽ lu&ocirc;n mang lại sự ch&iacute;nh x&aacute;c, đảm bảo v&agrave; tuyệt đối an to&agrave;n cho Qu&yacute; kh&aacute;ch.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span title=\"Tiết kiệm thời gian: Tourcoach liên tục cập nhật các thông tin về tất cả các chuyến bay, giờ bay, giá vé của 3 hãng hàng không nội địa, 300 hãng hàng không quốc tế.\">Save time: Tourcoach constantly updated information about all flights, flight times, fares of domestic airlines 3, 300 international airlines. </span><span title=\"Quý khách sẽ không cần phải tốn thời gian truy cập vào trang bán vé trực tuyến của từng hãng hàng không, chỉ cần một vài cú click chuột tra cứu thông tin, quý khách sẽ dễ dàng tìm kiếm được hành trình bay, so sánh giá\">You will not need to take time to visit online ticket sales of each airline, just a few mouse clicks information lookup, you will easily searchable itinerary, price comparison </span><span title=\"vé và thực hiện thao tác đặt vé, thanh toán trực tuyến một cách nhanh chóng.\">and perform a ticket booking, online payment quickly. </span><span title=\"Tiết kiệm chi phí: Việc cập nhật các thông tin khuyến mãi, so sánh giá vé của các hãng hàng không sẽ giúp Quý khách lựa chọn được chuyến bay có mức chi phí tiết kiệm nhất phù hợp với nhu cầu của mình.\">Cost savings: The information updated promotions, compare fares of the airlines will help you choose the flights with the best cost-saving suit your needs. </span><span title=\"Giá vé máy bay tốt nhất luôn luôn sẵn sàng cho Quý khách lựa chọn khi đặt dịch vụ ở Tourcoach.

\">The best airfares always ready for you to choose the services put in Tourcoach.</span><br />
	<br />
	<span title=\"Dễ dàng sử dụng: Quý khách có thể tìm thấy những thông tin hữu ích về vé máy bay ở Tourcoach qua từng chuyên mục: Tìm kiếm chuyến bay, Vé Quốc tế, Vé Nội địa, Tin khuyến mại, Vé máy bay theo chặng hành\">Easy to use: you can find useful information on flights in Tourcoach through each category: Search Flights, International Flights, Domestic Flights, Promotion, under the leg operating Airfare </span><span title=\"trình, Vé máy bay theo hãng hàng không để có thể lựa chọn hành trình bay phù hợp với mình.

\">Buildings, Flights by airline to choose the itinerary that suits you.</span><br />
	<br />
	<span title=\"Dịch vụ khách hàng chuyên nghiệp, tận tình: Đến với Vegiare, Quý khách luôn được đón chào nồng nhiệt, phục vụ chu đáo bởi đội ngũ nhân viên chuyên nghiệp, giàu nhiệt huyết và giỏi chuyên môn.\">Professional customer service, dedicated: To Vegiare, you always get a warm welcome, attentive service by a professional staff, enthusiastic and skilled professionals. </span><span title=\"Hệ thống chăm sóc khách hàng 24/7 luôn luôn sẵn sàng gải đáp mọi thắc mắc và hỗ trợ Quý khách về mặt nghiệp vụ.

\">Customer care system is always available 24/7 to answer any questions scrabble and support customers in terms of business.</span><br />
	<br />
	<span title=\"Thanh toán nhanh chóng, linh hoạt và an toàn: Quý khách có thể thanh toán trực tiếp qua chuyển khoản, tiền mặt.\">Paying fast, flexible and safe: You can pay directly through bank transfer, cash. </span><span title=\"Hệ thống thanh toán trực tuyến cho phép thanh toán bằng thẻ quốc tế Visa, Master Card, thẻ ngân hàng nội địa hoặc thanh toán qua mobile banking.\">Online payment system that allows payment by VISA, Master Card, domestic bank card or payment through mobile banking. </span><span title=\"Hệ thống bảo mật của Tourcoach cam kết sẽ luôn mang lại sự chính xác, đảm bảo và tuyệt đối an toàn cho Quý khách.\">Tourcoach system&#39;s security commitment will always bring accurate, absolute assurance and safety for the customer.</span></span></p>
','<p>
	Tourcoach chuy&ecirc;n cung cấp dịch vụ b&aacute;n v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, quốc tế v&agrave; tư vẫn hỗ trợ kh&aacute;ch h&agrave;ng chọn đường bay tốt, ph&ugrave; hợp với nhu cầu, rẻ v&agrave; chất lượng.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">specialized</span> <span class=\"hps\">service providers</span> <span class=\"hps\">to sell tickets</span> <span class=\"hps\">online</span> <span class=\"hps\">of</span> <span class=\"hps\">domestic</span> <span class=\"hps\">airlines</span><span>,</span> <span class=\"hps\">international</span> <span class=\"hps\">and</span> <span class=\"hps\">investment</span> <span class=\"hps\">still support</span> <span class=\"hps\">customers choose</span> <span class=\"hps\">better</span> <span class=\"hps\">routes</span><span>, in line with</span> <span class=\"hps\">demand</span><span>,</span> <span class=\"hps\">cheap</span> <span class=\"hps\">and</span> <span class=\"hps\">quality</span><span>.</span></span></p>
','<p>
	Tourcoach cam kết lu&ocirc;n nỗ lực x&acirc;y dựng v&agrave; cải tiến c&ocirc;ng nghệ, chất lượng dịch vụ để đem đến cho Qu&yacute; kh&aacute;ch những chuyến đi an to&agrave;n, chất lượng v&agrave; tiết kiệm.</p>
<p>
	Lấy &yacute; kiến kh&aacute;ch h&agrave;ng l&agrave;m trọng t&acirc;m cho hoạt động cải tiến chất lượng của c&ocirc;ng ty, nhằm n&acirc;ng cao hơn nữa sự tin tưởng của kh&aacute;ch h&agrave;ng đối với mỗi dịch vụ của Tourcoach, x&acirc;y dựng v&agrave; duy tr&igrave; thương hiệu của c&ocirc;ng ty trong l&ograve;ng kh&aacute;ch h&agrave;ng.</p>
','<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">committed to</span> <span class=\"hps\">efforts to build</span> <span class=\"hps\">and</span> <span class=\"hps\">improve technology</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">service</span> <span class=\"hps\">to</span> <span class=\"hps\">give</span> <span class=\"hps\">you</span> <span class=\"hps\">a safe</span> <span class=\"hps\">trip</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">and</span> <span class=\"hps\">savings</span><span>.</span><br />
	<br />
	<span class=\"hps\">Get the</span> <span class=\"hps\">customer</span> <span class=\"hps\">is</span> <span class=\"hps\">at the center of</span> <span class=\"hps\">quality</span> <span class=\"hps\">improvement activities</span> <span class=\"hps\">of the</span> <span class=\"hps\">company</span><span>,</span> <span class=\"hps\">in order</span> <span class=\"hps\">to further enhance</span> <span class=\"hps\">the trust of</span> <span class=\"hps\">customers for</span> <span class=\"hps\">each</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span> <span class=\"hps\">services</span><span>,</span> <span class=\"hps\">build</span> <span class=\"hps\">and</span> <span class=\"hps\">maintain</span> <span class=\"hps\">the company&#39;s</span> <span class=\"hps\">brand</span> <span class=\"hps\">in the hearts</span> <span class=\"hps\">customer.</span></span></p>
');
update gioithieu set Name='Thông tin giới thiệu',Img='/pi_maybay/view/admin/Themes/kcfinder/upload/images/gioithieu/img-post.jpg',GioiThieu='<p>
	TOURCOACH chuy&ecirc;n cung cấp dịch vụ đặt v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa v&agrave; quốc tế với c&aacute;c chức năng ưu việt: t&igrave;m kiếm h&agrave;nh tr&igrave;nh bay, giờ bay, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng, đặt v&eacute; tr&ecirc;n website v&agrave; thanh to&aacute;n trực tuyến.</p>
<p>
	Tourcoach được h&agrave;nh lập năm 2014 bởi C&Ocirc;NG TY TNHH DỊCH VỤ - VẬN TẢI V&Agrave; LỮ H&Agrave;NH QUỐC TẾ COACH, ch&uacute;ng t&ocirc;i đ&atilde; lựa chọn sứ mệnh phục vụ kh&aacute;ch h&agrave;ng mang đến những chuyến bay &ldquo;Chi ph&iacute; hợp l&yacute; &ndash; Chuyến đi như &yacute;&rdquo; - đ&oacute; ch&iacute;nh l&agrave; sự kh&aacute;c biệt của Tourcoach.</p>
',GioiThieu_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">TOURCOACH</span> <span class=\"hps\">specializes in providing</span> <span class=\"hps\">services</span> <span class=\"hps\">online</span> <span class=\"hps\">ticket booking</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span> <span class=\"hps\">domestic</span> <span class=\"hps\">and</span> <span class=\"hps\">international</span> <span class=\"hps\">with</span> <span class=\"hps\">Vietnam</span> <span class=\"hps\">enhanced functions</span><span>:</span> <span class=\"hps\">search for</span> <span class=\"hps\">the flight</span><span>,</span> <span class=\"hps\">flight times</span><span>,</span> <span class=\"hps\">compare</span> <span class=\"hps\">fares</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span><span>, ticketing</span> <span class=\"hps\">on the website</span> <span class=\"hps\">and</span> <span class=\"hps\">pay online</span><span>.</span><br />
	<br />
	<span class=\"hps\">Tourcoach</span> <span class=\"hps\">was</span> <span class=\"hps\">founded</span> <span class=\"hps\">in 2014</span> <span class=\"hps\">by</span> <span class=\"hps\">executive</span> <span class=\"hps\">SERVICES LIMITED</span> <span class=\"hps\">COMPANY</span> <span class=\"hps\">-</span> <span class=\"hps\">TRANSPORTATION AND</span> <span class=\"hps\">TRAVEL</span> <span class=\"hps\">INTERNATIONAL</span> <span class=\"hps\">COACH</span><span>,</span> <span class=\"hps\">we</span> <span class=\"hps\">have chosen</span> <span class=\"hps\">the mission</span> <span class=\"hps\">to serve customers</span> <span class=\"hps\">bring</span> <span class=\"hps\">flight</span> <span class=\"hps atn\">&quot;</span><span>Reasonable expenses</span> <span class=\"hps\">-</span> <span class=\"hps\">Trips</span> <span class=\"hps\">like that</span><span>&quot;</span> <span class=\"hps\">-</span> <span class=\"hps\">that is the</span> <span class=\"hps\">difference</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span><span>.</span></span></p>
',UuViet='<p>
	Tiết kiệm thời gian: Tourcoach li&ecirc;n tục cập nhật c&aacute;c th&ocirc;ng tin về tất cả c&aacute;c chuyến bay, giờ bay, gi&aacute; v&eacute; của 3 h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, 300 h&atilde;ng h&agrave;ng kh&ocirc;ng quốc tế. Qu&yacute; kh&aacute;ch sẽ kh&ocirc;ng cần phải tốn thời gian truy cập v&agrave;o trang b&aacute;n v&eacute; trực tuyến của từng h&atilde;ng h&agrave;ng kh&ocirc;ng, chỉ cần một v&agrave;i c&uacute; click chuột tra cứu th&ocirc;ng tin, qu&yacute; kh&aacute;ch sẽ dễ d&agrave;ng t&igrave;m kiếm được h&agrave;nh tr&igrave;nh bay, so s&aacute;nh gi&aacute; v&eacute; v&agrave; thực hiện thao t&aacute;c đặt v&eacute;, thanh to&aacute;n trực tuyến một c&aacute;ch nhanh ch&oacute;ng. Tiết kiệm chi ph&iacute;: Việc cập nhật c&aacute;c th&ocirc;ng tin khuyến m&atilde;i, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng sẽ gi&uacute;p Qu&yacute; kh&aacute;ch lựa chọn được chuyến bay c&oacute; mức chi ph&iacute; tiết kiệm nhất ph&ugrave; hợp với nhu cầu của m&igrave;nh. Gi&aacute; v&eacute; m&aacute;y bay tốt nhất lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng cho Qu&yacute; kh&aacute;ch lựa chọn khi đặt dịch vụ ở Tourcoach.</p>
<p>
	Dễ d&agrave;ng sử dụng: Qu&yacute; kh&aacute;ch c&oacute; thể t&igrave;m thấy những th&ocirc;ng tin hữu &iacute;ch về v&eacute; m&aacute;y bay ở Tourcoach qua từng chuy&ecirc;n mục: T&igrave;m kiếm chuyến bay, V&eacute; Quốc tế, V&eacute; Nội địa, Tin khuyến mại, V&eacute; m&aacute;y bay theo chặng h&agrave;nh tr&igrave;nh, V&eacute; m&aacute;y bay theo h&atilde;ng h&agrave;ng kh&ocirc;ng để c&oacute; thể lựa chọn h&agrave;nh tr&igrave;nh bay ph&ugrave; hợp với m&igrave;nh.</p>
<p>
	Dịch vụ kh&aacute;ch h&agrave;ng chuy&ecirc;n nghiệp, tận t&igrave;nh: Đến với Vegiare, Qu&yacute; kh&aacute;ch lu&ocirc;n được đ&oacute;n ch&agrave;o nồng nhiệt, phục vụ chu đ&aacute;o bởi đội ngũ nh&acirc;n vi&ecirc;n chuy&ecirc;n nghiệp, gi&agrave;u nhiệt huyết v&agrave; giỏi chuy&ecirc;n m&ocirc;n. Hệ thống chăm s&oacute;c kh&aacute;ch h&agrave;ng 24/7 lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng gải đ&aacute;p mọi thắc mắc v&agrave; hỗ trợ Qu&yacute; kh&aacute;ch về mặt nghiệp vụ.</p>
<p>
	Thanh to&aacute;n nhanh ch&oacute;ng, linh hoạt v&agrave; an to&agrave;n: Qu&yacute; kh&aacute;ch c&oacute; thể thanh to&aacute;n trực tiếp qua chuyển khoản, tiền mặt. Hệ thống thanh to&aacute;n trực tuyến cho ph&eacute;p thanh to&aacute;n bằng thẻ quốc tế Visa, Master Card, thẻ ng&acirc;n h&agrave;ng nội địa hoặc thanh to&aacute;n qua mobile banking. Hệ thống bảo mật của Tourcoach cam kết sẽ lu&ocirc;n mang lại sự ch&iacute;nh x&aacute;c, đảm bảo v&agrave; tuyệt đối an to&agrave;n cho Qu&yacute; kh&aacute;ch.</p>
',UuViet_en='<p>
	<span id=\"result_box\" lang=\"en\"><span title=\"Tiết kiệm thời gian: Tourcoach liên tục cập nhật các thông tin về tất cả các chuyến bay, giờ bay, giá vé của 3 hãng hàng không nội địa, 300 hãng hàng không quốc tế.\">Save time: Tourcoach constantly updated information about all flights, flight times, fares of domestic airlines 3, 300 international airlines. </span><span title=\"Quý khách sẽ không cần phải tốn thời gian truy cập vào trang bán vé trực tuyến của từng hãng hàng không, chỉ cần một vài cú click chuột tra cứu thông tin, quý khách sẽ dễ dàng tìm kiếm được hành trình bay, so sánh giá\">You will not need to take time to visit online ticket sales of each airline, just a few mouse clicks information lookup, you will easily searchable itinerary, price comparison </span><span title=\"vé và thực hiện thao tác đặt vé, thanh toán trực tuyến một cách nhanh chóng.\">and perform a ticket booking, online payment quickly. </span><span title=\"Tiết kiệm chi phí: Việc cập nhật các thông tin khuyến mãi, so sánh giá vé của các hãng hàng không sẽ giúp Quý khách lựa chọn được chuyến bay có mức chi phí tiết kiệm nhất phù hợp với nhu cầu của mình.\">Cost savings: The information updated promotions, compare fares of the airlines will help you choose the flights with the best cost-saving suit your needs. </span><span title=\"Giá vé máy bay tốt nhất luôn luôn sẵn sàng cho Quý khách lựa chọn khi đặt dịch vụ ở Tourcoach.

\">The best airfares always ready for you to choose the services put in Tourcoach.</span><br />
	<br />
	<span title=\"Dễ dàng sử dụng: Quý khách có thể tìm thấy những thông tin hữu ích về vé máy bay ở Tourcoach qua từng chuyên mục: Tìm kiếm chuyến bay, Vé Quốc tế, Vé Nội địa, Tin khuyến mại, Vé máy bay theo chặng hành\">Easy to use: you can find useful information on flights in Tourcoach through each category: Search Flights, International Flights, Domestic Flights, Promotion, under the leg operating Airfare </span><span title=\"trình, Vé máy bay theo hãng hàng không để có thể lựa chọn hành trình bay phù hợp với mình.

\">Buildings, Flights by airline to choose the itinerary that suits you.</span><br />
	<br />
	<span title=\"Dịch vụ khách hàng chuyên nghiệp, tận tình: Đến với Vegiare, Quý khách luôn được đón chào nồng nhiệt, phục vụ chu đáo bởi đội ngũ nhân viên chuyên nghiệp, giàu nhiệt huyết và giỏi chuyên môn.\">Professional customer service, dedicated: To Vegiare, you always get a warm welcome, attentive service by a professional staff, enthusiastic and skilled professionals. </span><span title=\"Hệ thống chăm sóc khách hàng 24/7 luôn luôn sẵn sàng gải đáp mọi thắc mắc và hỗ trợ Quý khách về mặt nghiệp vụ.

\">Customer care system is always available 24/7 to answer any questions scrabble and support customers in terms of business.</span><br />
	<br />
	<span title=\"Thanh toán nhanh chóng, linh hoạt và an toàn: Quý khách có thể thanh toán trực tiếp qua chuyển khoản, tiền mặt.\">Paying fast, flexible and safe: You can pay directly through bank transfer, cash. </span><span title=\"Hệ thống thanh toán trực tuyến cho phép thanh toán bằng thẻ quốc tế Visa, Master Card, thẻ ngân hàng nội địa hoặc thanh toán qua mobile banking.\">Online payment system that allows payment by VISA, Master Card, domestic bank card or payment through mobile banking. </span><span title=\"Hệ thống bảo mật của Tourcoach cam kết sẽ luôn mang lại sự chính xác, đảm bảo và tuyệt đối an toàn cho Quý khách.\">Tourcoach system&#39;s security commitment will always bring accurate, absolute assurance and safety for the customer.</span></span></p>
',CacDichVu='<p>
	Tourcoach chuy&ecirc;n cung cấp dịch vụ b&aacute;n v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, quốc tế v&agrave; tư vẫn hỗ trợ kh&aacute;ch h&agrave;ng chọn đường bay tốt, ph&ugrave; hợp với nhu cầu, rẻ v&agrave; chất lượng.</p>
',CacDicVu_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">specialized</span> <span class=\"hps\">service providers</span> <span class=\"hps\">to sell tickets</span> <span class=\"hps\">online</span> <span class=\"hps\">of</span> <span class=\"hps\">domestic</span> <span class=\"hps\">airlines</span><span>,</span> <span class=\"hps\">international</span> <span class=\"hps\">and</span> <span class=\"hps\">investment</span> <span class=\"hps\">still support</span> <span class=\"hps\">customers choose</span> <span class=\"hps\">better</span> <span class=\"hps\">routes</span><span>, in line with</span> <span class=\"hps\">demand</span><span>,</span> <span class=\"hps\">cheap</span> <span class=\"hps\">and</span> <span class=\"hps\">quality</span><span>.</span></span></p>
',CamKet='<p>
	Tourcoach cam kết lu&ocirc;n nỗ lực x&acirc;y dựng v&agrave; cải tiến c&ocirc;ng nghệ, chất lượng dịch vụ để đem đến cho Qu&yacute; kh&aacute;ch những chuyến đi an to&agrave;n, chất lượng v&agrave; tiết kiệm.</p>
<p>
	Lấy &yacute; kiến kh&aacute;ch h&agrave;ng l&agrave;m trọng t&acirc;m cho hoạt động cải tiến chất lượng của c&ocirc;ng ty, nhằm n&acirc;ng cao hơn nữa sự tin tưởng của kh&aacute;ch h&agrave;ng đối với mỗi dịch vụ của Tourcoach, x&acirc;y dựng v&agrave; duy tr&igrave; thương hiệu của c&ocirc;ng ty trong l&ograve;ng kh&aacute;ch h&agrave;ng.</p>
',CamKet_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">committed to</span> <span class=\"hps\">efforts to build</span> <span class=\"hps\">and</span> <span class=\"hps\">improve technology</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">service</span> <span class=\"hps\">to</span> <span class=\"hps\">give</span> <span class=\"hps\">you</span> <span class=\"hps\">a safe</span> <span class=\"hps\">trip</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">and</span> <span class=\"hps\">savings</span><span>.</span><br />
	<br />
	<span class=\"hps\">Get the</span> <span class=\"hps\">customer</span> <span class=\"hps\">is</span> <span class=\"hps\">at the center of</span> <span class=\"hps\">quality</span> <span class=\"hps\">improvement activities</span> <span class=\"hps\">of the</span> <span class=\"hps\">company</span><span>,</span> <span class=\"hps\">in order</span> <span class=\"hps\">to further enhance</span> <span class=\"hps\">the trust of</span> <span class=\"hps\">customers for</span> <span class=\"hps\">each</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span> <span class=\"hps\">services</span><span>,</span> <span class=\"hps\">build</span> <span class=\"hps\">and</span> <span class=\"hps\">maintain</span> <span class=\"hps\">the company&#39;s</span> <span class=\"hps\">brand</span> <span class=\"hps\">in the hearts</span> <span class=\"hps\">customer.</span></span></p>
' where Id=1;
update gioithieu set Name='Thông tin giới thiệu',Img='/pi_maybay/view/admin/Themes/kcfinder/upload/images/gioithieu/img-post.jpg',GioiThieu='<p>
	TOURCOACH chuy&ecirc;n cung cấp dịch vụ đặt v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa v&agrave; quốc tế với c&aacute;c chức năng ưu việt: t&igrave;m kiếm h&agrave;nh tr&igrave;nh bay, giờ bay, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng, đặt v&eacute; tr&ecirc;n website v&agrave; thanh to&aacute;n trực tuyến.</p>
<p>
	Tourcoach được h&agrave;nh lập năm 2014 bởi C&Ocirc;NG TY TNHH DỊCH VỤ - VẬN TẢI V&Agrave; LỮ H&Agrave;NH QUỐC TẾ COACH, ch&uacute;ng t&ocirc;i đ&atilde; lựa chọn sứ mệnh phục vụ kh&aacute;ch h&agrave;ng mang đến những chuyến bay &ldquo;Chi ph&iacute; hợp l&yacute; &ndash; Chuyến đi như &yacute;&rdquo; - đ&oacute; ch&iacute;nh l&agrave; sự kh&aacute;c biệt của Tourcoach.</p>
',GioiThieu_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">TOURCOACH</span> <span class=\"hps\">specializes in providing</span> <span class=\"hps\">services</span> <span class=\"hps\">online</span> <span class=\"hps\">ticket booking</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span> <span class=\"hps\">domestic</span> <span class=\"hps\">and</span> <span class=\"hps\">international</span> <span class=\"hps\">with</span> <span class=\"hps\">Vietnam</span> <span class=\"hps\">enhanced functions</span><span>:</span> <span class=\"hps\">search for</span> <span class=\"hps\">the flight</span><span>,</span> <span class=\"hps\">flight times</span><span>,</span> <span class=\"hps\">compare</span> <span class=\"hps\">fares</span> <span class=\"hps\">of</span> <span class=\"hps\">airlines</span><span>, ticketing</span> <span class=\"hps\">on the website</span> <span class=\"hps\">and</span> <span class=\"hps\">pay online</span><span>.</span><br />
	<br />
	<span class=\"hps\">Tourcoach</span> <span class=\"hps\">was</span> <span class=\"hps\">founded</span> <span class=\"hps\">in 2014</span> <span class=\"hps\">by</span> <span class=\"hps\">executive</span> <span class=\"hps\">SERVICES LIMITED</span> <span class=\"hps\">COMPANY</span> <span class=\"hps\">-</span> <span class=\"hps\">TRANSPORTATION AND</span> <span class=\"hps\">TRAVEL</span> <span class=\"hps\">INTERNATIONAL</span> <span class=\"hps\">COACH</span><span>,</span> <span class=\"hps\">we</span> <span class=\"hps\">have chosen</span> <span class=\"hps\">the mission</span> <span class=\"hps\">to serve customers</span> <span class=\"hps\">bring</span> <span class=\"hps\">flight</span> <span class=\"hps atn\">&quot;</span><span>Reasonable expenses</span> <span class=\"hps\">-</span> <span class=\"hps\">Trips</span> <span class=\"hps\">like that</span><span>&quot;</span> <span class=\"hps\">-</span> <span class=\"hps\">that is the</span> <span class=\"hps\">difference</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span><span>.</span></span></p>
',UuViet='<p>
	Tiết kiệm thời gian: Tourcoach li&ecirc;n tục cập nhật c&aacute;c th&ocirc;ng tin về tất cả c&aacute;c chuyến bay, giờ bay, gi&aacute; v&eacute; của 3 h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, 300 h&atilde;ng h&agrave;ng kh&ocirc;ng quốc tế. Qu&yacute; kh&aacute;ch sẽ kh&ocirc;ng cần phải tốn thời gian truy cập v&agrave;o trang b&aacute;n v&eacute; trực tuyến của từng h&atilde;ng h&agrave;ng kh&ocirc;ng, chỉ cần một v&agrave;i c&uacute; click chuột tra cứu th&ocirc;ng tin, qu&yacute; kh&aacute;ch sẽ dễ d&agrave;ng t&igrave;m kiếm được h&agrave;nh tr&igrave;nh bay, so s&aacute;nh gi&aacute; v&eacute; v&agrave; thực hiện thao t&aacute;c đặt v&eacute;, thanh to&aacute;n trực tuyến một c&aacute;ch nhanh ch&oacute;ng. Tiết kiệm chi ph&iacute;: Việc cập nhật c&aacute;c th&ocirc;ng tin khuyến m&atilde;i, so s&aacute;nh gi&aacute; v&eacute; của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng sẽ gi&uacute;p Qu&yacute; kh&aacute;ch lựa chọn được chuyến bay c&oacute; mức chi ph&iacute; tiết kiệm nhất ph&ugrave; hợp với nhu cầu của m&igrave;nh. Gi&aacute; v&eacute; m&aacute;y bay tốt nhất lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng cho Qu&yacute; kh&aacute;ch lựa chọn khi đặt dịch vụ ở Tourcoach.</p>
<p>
	Dễ d&agrave;ng sử dụng: Qu&yacute; kh&aacute;ch c&oacute; thể t&igrave;m thấy những th&ocirc;ng tin hữu &iacute;ch về v&eacute; m&aacute;y bay ở Tourcoach qua từng chuy&ecirc;n mục: T&igrave;m kiếm chuyến bay, V&eacute; Quốc tế, V&eacute; Nội địa, Tin khuyến mại, V&eacute; m&aacute;y bay theo chặng h&agrave;nh tr&igrave;nh, V&eacute; m&aacute;y bay theo h&atilde;ng h&agrave;ng kh&ocirc;ng để c&oacute; thể lựa chọn h&agrave;nh tr&igrave;nh bay ph&ugrave; hợp với m&igrave;nh.</p>
<p>
	Dịch vụ kh&aacute;ch h&agrave;ng chuy&ecirc;n nghiệp, tận t&igrave;nh: Đến với Vegiare, Qu&yacute; kh&aacute;ch lu&ocirc;n được đ&oacute;n ch&agrave;o nồng nhiệt, phục vụ chu đ&aacute;o bởi đội ngũ nh&acirc;n vi&ecirc;n chuy&ecirc;n nghiệp, gi&agrave;u nhiệt huyết v&agrave; giỏi chuy&ecirc;n m&ocirc;n. Hệ thống chăm s&oacute;c kh&aacute;ch h&agrave;ng 24/7 lu&ocirc;n lu&ocirc;n sẵn s&agrave;ng gải đ&aacute;p mọi thắc mắc v&agrave; hỗ trợ Qu&yacute; kh&aacute;ch về mặt nghiệp vụ.</p>
<p>
	Thanh to&aacute;n nhanh ch&oacute;ng, linh hoạt v&agrave; an to&agrave;n: Qu&yacute; kh&aacute;ch c&oacute; thể thanh to&aacute;n trực tiếp qua chuyển khoản, tiền mặt. Hệ thống thanh to&aacute;n trực tuyến cho ph&eacute;p thanh to&aacute;n bằng thẻ quốc tế Visa, Master Card, thẻ ng&acirc;n h&agrave;ng nội địa hoặc thanh to&aacute;n qua mobile banking. Hệ thống bảo mật của Tourcoach cam kết sẽ lu&ocirc;n mang lại sự ch&iacute;nh x&aacute;c, đảm bảo v&agrave; tuyệt đối an to&agrave;n cho Qu&yacute; kh&aacute;ch.</p>
',UuViet_en='<p>
	<span id=\"result_box\" lang=\"en\"><span title=\"Tiết kiệm thời gian: Tourcoach liên tục cập nhật các thông tin về tất cả các chuyến bay, giờ bay, giá vé của 3 hãng hàng không nội địa, 300 hãng hàng không quốc tế.\">Save time: Tourcoach constantly updated information about all flights, flight times, fares of domestic airlines 3, 300 international airlines. </span><span title=\"Quý khách sẽ không cần phải tốn thời gian truy cập vào trang bán vé trực tuyến của từng hãng hàng không, chỉ cần một vài cú click chuột tra cứu thông tin, quý khách sẽ dễ dàng tìm kiếm được hành trình bay, so sánh giá\">You will not need to take time to visit online ticket sales of each airline, just a few mouse clicks information lookup, you will easily searchable itinerary, price comparison </span><span title=\"vé và thực hiện thao tác đặt vé, thanh toán trực tuyến một cách nhanh chóng.\">and perform a ticket booking, online payment quickly. </span><span title=\"Tiết kiệm chi phí: Việc cập nhật các thông tin khuyến mãi, so sánh giá vé của các hãng hàng không sẽ giúp Quý khách lựa chọn được chuyến bay có mức chi phí tiết kiệm nhất phù hợp với nhu cầu của mình.\">Cost savings: The information updated promotions, compare fares of the airlines will help you choose the flights with the best cost-saving suit your needs. </span><span title=\"Giá vé máy bay tốt nhất luôn luôn sẵn sàng cho Quý khách lựa chọn khi đặt dịch vụ ở Tourcoach.

\">The best airfares always ready for you to choose the services put in Tourcoach.</span><br />
	<br />
	<span title=\"Dễ dàng sử dụng: Quý khách có thể tìm thấy những thông tin hữu ích về vé máy bay ở Tourcoach qua từng chuyên mục: Tìm kiếm chuyến bay, Vé Quốc tế, Vé Nội địa, Tin khuyến mại, Vé máy bay theo chặng hành\">Easy to use: you can find useful information on flights in Tourcoach through each category: Search Flights, International Flights, Domestic Flights, Promotion, under the leg operating Airfare </span><span title=\"trình, Vé máy bay theo hãng hàng không để có thể lựa chọn hành trình bay phù hợp với mình.

\">Buildings, Flights by airline to choose the itinerary that suits you.</span><br />
	<br />
	<span title=\"Dịch vụ khách hàng chuyên nghiệp, tận tình: Đến với Vegiare, Quý khách luôn được đón chào nồng nhiệt, phục vụ chu đáo bởi đội ngũ nhân viên chuyên nghiệp, giàu nhiệt huyết và giỏi chuyên môn.\">Professional customer service, dedicated: To Vegiare, you always get a warm welcome, attentive service by a professional staff, enthusiastic and skilled professionals. </span><span title=\"Hệ thống chăm sóc khách hàng 24/7 luôn luôn sẵn sàng gải đáp mọi thắc mắc và hỗ trợ Quý khách về mặt nghiệp vụ.

\">Customer care system is always available 24/7 to answer any questions scrabble and support customers in terms of business.</span><br />
	<br />
	<span title=\"Thanh toán nhanh chóng, linh hoạt và an toàn: Quý khách có thể thanh toán trực tiếp qua chuyển khoản, tiền mặt.\">Paying fast, flexible and safe: You can pay directly through bank transfer, cash. </span><span title=\"Hệ thống thanh toán trực tuyến cho phép thanh toán bằng thẻ quốc tế Visa, Master Card, thẻ ngân hàng nội địa hoặc thanh toán qua mobile banking.\">Online payment system that allows payment by VISA, Master Card, domestic bank card or payment through mobile banking. </span><span title=\"Hệ thống bảo mật của Tourcoach cam kết sẽ luôn mang lại sự chính xác, đảm bảo và tuyệt đối an toàn cho Quý khách.\">Tourcoach system&#39;s security commitment will always bring accurate, absolute assurance and safety for the customer.</span></span></p>
',CacDichVu='<p>
	Tourcoach chuy&ecirc;n cung cấp dịch vụ b&aacute;n v&eacute; m&aacute;y bay trực tuyến của c&aacute;c h&atilde;ng h&agrave;ng kh&ocirc;ng nội địa, quốc tế v&agrave; tư vẫn hỗ trợ kh&aacute;ch h&agrave;ng chọn đường bay tốt, ph&ugrave; hợp với nhu cầu, rẻ v&agrave; chất lượng.</p>
',CacDicVu_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">specialized</span> <span class=\"hps\">service providers</span> <span class=\"hps\">to sell tickets</span> <span class=\"hps\">online</span> <span class=\"hps\">of</span> <span class=\"hps\">domestic</span> <span class=\"hps\">airlines</span><span>,</span> <span class=\"hps\">international</span> <span class=\"hps\">and</span> <span class=\"hps\">investment</span> <span class=\"hps\">still support</span> <span class=\"hps\">customers choose</span> <span class=\"hps\">better</span> <span class=\"hps\">routes</span><span>, in line with</span> <span class=\"hps\">demand</span><span>,</span> <span class=\"hps\">cheap</span> <span class=\"hps\">and</span> <span class=\"hps\">quality</span><span>.</span></span></p>
',CamKet='<p>
	Tourcoach cam kết lu&ocirc;n nỗ lực x&acirc;y dựng v&agrave; cải tiến c&ocirc;ng nghệ, chất lượng dịch vụ để đem đến cho Qu&yacute; kh&aacute;ch những chuyến đi an to&agrave;n, chất lượng v&agrave; tiết kiệm.</p>
<p>
	Lấy &yacute; kiến kh&aacute;ch h&agrave;ng l&agrave;m trọng t&acirc;m cho hoạt động cải tiến chất lượng của c&ocirc;ng ty, nhằm n&acirc;ng cao hơn nữa sự tin tưởng của kh&aacute;ch h&agrave;ng đối với mỗi dịch vụ của Tourcoach, x&acirc;y dựng v&agrave; duy tr&igrave; thương hiệu của c&ocirc;ng ty trong l&ograve;ng kh&aacute;ch h&agrave;ng.</p>
',CamKet_en='<p>
	<span id=\"result_box\" lang=\"en\"><span class=\"hps\">Tourcoach</span> <span class=\"hps\">committed to</span> <span class=\"hps\">efforts to build</span> <span class=\"hps\">and</span> <span class=\"hps\">improve technology</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">service</span> <span class=\"hps\">to</span> <span class=\"hps\">give</span> <span class=\"hps\">you</span> <span class=\"hps\">a safe</span> <span class=\"hps\">trip</span><span>,</span> <span class=\"hps\">quality</span> <span class=\"hps\">and</span> <span class=\"hps\">savings</span><span>.</span><br />
	<br />
	<span class=\"hps\">Get the</span> <span class=\"hps\">customer</span> <span class=\"hps\">is</span> <span class=\"hps\">at the center of</span> <span class=\"hps\">quality</span> <span class=\"hps\">improvement activities</span> <span class=\"hps\">of the</span> <span class=\"hps\">company</span><span>,</span> <span class=\"hps\">in order</span> <span class=\"hps\">to further enhance</span> <span class=\"hps\">the trust of</span> <span class=\"hps\">customers for</span> <span class=\"hps\">each</span> <span class=\"hps\">of</span> <span class=\"hps\">Tourcoach</span> <span class=\"hps\">services</span><span>,</span> <span class=\"hps\">build</span> <span class=\"hps\">and</span> <span class=\"hps\">maintain</span> <span class=\"hps\">the company&#39;s</span> <span class=\"hps\">brand</span> <span class=\"hps\">in the hearts</span> <span class=\"hps\">customer.</span></span></p>
',LienHe='<p>
	<span style=\"color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\">Địa chỉ: B44 Nguyễn Thị Định, Trung H&ograve;a - Nh&acirc;n Ch&iacute;nh, H&agrave; Nội</span><br style=\"box-sizing: border-box; color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\" />
	<span style=\"color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\">Điện thoại: (+84) 439 28 3441 Fax: (+84) 439 28 3443</span><br style=\"box-sizing: border-box; color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\" />
	<span style=\"color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\">Giấy chứng nhận Đăng k&yacute; Kinh doanh số 0309532909</span><br style=\"box-sizing: border-box; color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\" />
	<span style=\"color: rgb(51, 51, 51); font-family: \'Helvetica Neue\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px;\">Do Sở Kế hoạch v&agrave; Đầu tư Th&agrave;nh phố H&agrave; Nội cấp ng&agrave;y 28/05/2014</span></p>
',LienHe_en='<div>
	Address: B44 Nguyen Thi Dinh Street, Trung Hoa - Nhan Chinh, Hanoi</div>
<div>
	Phone: (+84) 439 28 3441 Fax: (+84) 439 28 3443</div>
<div>
	Certificate No. 0309532909 Business Registration</div>
<div>
	By Department of Planning and Investment in Hanoi issued on 05.28.2014</div>
' where Id=1;
