update menu set Name='Giới thiệu',Name_en='About us',Title='Giới thiệu',Title_en='About us',Keyword='Giới thiệu',Description='Giới thiệu' where Id=1;
update menu set Name='Vé nội địa',Name_en='Domestic Flights',Title='Vé nội địa',Title_en='Domestic Flights',Keyword='Vé nội địa',Description='Thanh toán & giao hàng' where Id=2;
update menu set Name='Vé quốc tế',Name_en='International ticket',Title='Vé quốc tế',Title_en='International ticket',Keyword='Vé quốc tế',Description='Vé quốc tế' where Id=3;
update menu set Name='Vé nội địa',Name_en='Domestic ticket',Title='Vé nội địa',Title_en='Domestic ticket',Keyword='Vé nội địa',Description='Thanh toán & giao hàng' where Id=2;
update menu set Name='Dịch vụ',Name_en='Service',Title='Dịch vụ',Title_en='Service',Keyword='Dịch vụ',Description='Dịch vụ' where Id=4;
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Tin khuyến mãi','Promotion','Tin khuyến mãi','Promotion','Tin khuyến mãi','Tin khuyến mãi');
update menu set Name='Giới thiệu',Name_en=' Introduction',Title='Giới thiệu',Title_en=' Introduction',Keyword='Giới thiệu',Description='Giới thiệu' where Id=1;
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Liên hệ','Contact','Liên hệ','Contact','Liên hệ','Liên hệ');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Hỏi đáp','FAQ','Hỏi đáp','FAQ','Hỏi đáp','Hỏi đáp');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Điều khoản & điều kiện','Terms & Conditions','Điều khoản & điều kiện','Terms & Conditions','Điều khoản & điều kiện','Điều khoản & điều kiện');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Chính sách riêng tư','Privacy policy','Chính sách riêng tư','Privacy policy','Chính sách riêng tư','Chính sách riêng tư');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Hướng dẫn thanh toán','Payment instructions','Hướng dẫn thanh toán','Payment instructions','Hướng dẫn thanh toán','Hướng dẫn thanh toán');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Thông tin chuyển khoản','Information transfer','Thông tin chuyển khoản','Information transfer','Thông tin chuyển khoản','Thông tin chuyển khoản');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Đăng ký','Register','Đăng ký','Register','Đăng ký','Đăng ký');
update menu set Name='Đăng ký thành viên',Name_en='Sign up',Title='Đăng ký thành viên',Title_en='Sign up',Keyword='Đăng ký thành viên',Description='Đăng ký thành viên' where Id=12;
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Đăng ký thành công','Sign Up Success','Đăng ký thành công','Sign Up Success','Đăng ký thành công','Đăng ký thành công');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Tìm kiếm','Search','Tìm kiếm','Search','Tìm kiếm','Tìm kiếm');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Thông tin thanh toán','Billing Information','Thông tin thanh toán','Billing Information','Thông tin thanh toán','Thông tin thanh toán');
insert into menu (Name,Name_en,Title,Title_en,Keyword,Description) values ('Xác nhận thanh toán','Confirm payment','Xác nhận thanh toán','Confirm payment','Xác nhận thanh toán','Xác nhận thanh toán');
