insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-visa.jpg','');
update thanhtoan set Name='Visa',Name_en='Visa',Img='/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-visa.jpg',Link='' where Id=1;
insert into thanhtoan (Name,Name_en,Img,Link) values ('Onpay','Onpay','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-onepay.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-uniconpay.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-paypal.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-mastercard.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-jcb.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-discover.jpg','');
insert into thanhtoan (Name,Name_en,Img,Link) values ('','','/pi_maybay/view/admin/Themes/kcfinder/upload/images/thanhtoan/tt-american.jpg','');
